=== djnugent/cdn/schemas/new_this_year.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "description": {
                "type": "string"
            },
            "image": {
                "type": "string",
                "format": "uri"
            },
            "slug": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "format": "uuid"
            },
            "name": {
                "type": "string"
            },
            "vendor_slug": {
                "type": "string"
            }
        },
        "required": [
            "description",
            "image",
            "slug",
            "id",
            "name",
            "vendor_slug"
        ]
    }
}

=== djnugent/cdn/new_this_year.json
[
    {
        "description": "Serving craft mocktails and small bites. 100% you, 0% alcohol.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-11221.1.jpg",
        "slug": "6a307f77-b240-4fdd-ab1b-e703c67d353c",
        "id": "6a307f77-b240-4fdd-ab1b-e703c67d353c",
        "name": "Urban Glow Mocktails",
        "vendor_slug": "11221.1"
    },
    {
        "description": "Afro Bean Pops are handcrafted fritters made from finely ground black-eyed peas, blended with fresh onions, spices, and a touch of heat. Each bite bursts with savory flavor and a satisfying crunch. These classic black-eyed pea fritters are crunchy on the outside, fluffy inside, and infused with just the right balance of spices. Enjoy them solo or with a spicy chili red sauce",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-afro-bean-pops.jpg",
        "slug": "9beb9170-7580-4028-93df-51b4265900b1",
        "id": "9beb9170-7580-4028-93df-51b4265900b1",
        "name": "Afro Bean Pops",
        "vendor_slug": "7388.1"
    },
    {
        "description": "Homemade Whipped Feta topped with schug \u2014 a bold, Mediterranean spicy relish made from jalape\u00f1os, garlic, cilantro, and warm spices. It\u2019s finished with a drizzle of extra virgin olive oil and a sprinkle of toasted wild rice for added texture.\n\nServed with crispy deep-fried flatbread dusted in our signature Dino\u2019s Greek seasoning.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-athena's-whipped-feta.jpg",
        "slug": "2bbcfe1c-c7e5-4b3f-b430-85dae89e7a6c",
        "id": "2bbcfe1c-c7e5-4b3f-b430-85dae89e7a6c",
        "name": "Athena's Whipped Feta",
        "vendor_slug": "1457.1"
    },
    {
        "description": "It\u2019s officially time for the Sprinkle Party! Made from scratch cake batter cookie dough covered in a crunchy cake confetti she\u2019ll. Topped with rainbow sprinkles and served on a stick! It\u2019s sweet, crunchy and rainbow sprinkly Doughlicious! It\u2019s perfect for the whole family!",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-birthday-cake-cookie-dough-on-a-stick.jpg",
        "slug": "94a758ef-6030-4e86-9a03-95f1a16923d3",
        "id": "94a758ef-6030-4e86-9a03-95f1a16923d3",
        "name": "Birthday Cake Cookie Dough On-A-Stick",
        "vendor_slug": "3699.1"
    },
    {
        "description": "Bison and bacon meatballs, from Minnesota-based Eichten's Bison and Hidden Stream Farm, topped with bison gravy, quick-pickled cucumbers, crispy fried onions and sour cream. Served on a toasted wild rice hoagie bun.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-bison-meatball-sub.jpg",
        "slug": "c9ae79e0-33db-4bcb-adb7-3bd65af51e02",
        "id": "c9ae79e0-33db-4bcb-adb7-3bd65af51e02",
        "name": "Bison Meatball Sub",
        "vendor_slug": "2878.1"
    },
    {
        "description": "Cannoli chips topped with a scoop of cannoli-flavored gelato. Finished with chocolate sauce, rainbow sprinkles and a cherry!",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-cannoli-gelato-nachos.jpg",
        "slug": "f8d309e1-8a3b-48c4-a60f-66c257010393",
        "id": "f8d309e1-8a3b-48c4-a60f-66c257010393",
        "name": "Cannoli Gelato Nachos",
        "vendor_slug": "198.1"
    },
    {
        "description": "Mozzarella cheese curds breaded with Italian seasoning and deep fried. Served over a bruschetta-flavored blend of tomatoes and basil, and drizzled with balsamic glaze. Served with a side of crostini for scooping.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-caprese-curds.jpg",
        "slug": "d8023d05-c2f0-499d-87fa-b629007c8368",
        "id": "d8023d05-c2f0-499d-87fa-b629007c8368",
        "name": "Caprese Curds",
        "vendor_slug": "1416.1"
    },
    {
        "description": "Limeade juice topped with cherry Dole Soft Serve, garnished with a lime slice and a cherry.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-cherry-bigfoot-limeade-float.jpg",
        "slug": "8b953dfa-240f-4859-95fd-5e4b9d7b0a74",
        "id": "8b953dfa-240f-4859-95fd-5e4b9d7b0a74",
        "name": "Cherry Bigfoot Limeade Float",
        "vendor_slug": "8535.1"
    },
    {
        "description": "Freshly baked flaky pie crust strips covered in cinnamon and sugar. Served with a side of whiskey-flavored caramel dipping sauce.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-cinna-sugar-crust-tidbits.jpg",
        "slug": "60ce0f22-2267-49d9-b138-88abb57b8cd2",
        "id": "60ce0f22-2267-49d9-b138-88abb57b8cd2",
        "name": "Cinna-sugar Crust Tidbits",
        "vendor_slug": "1288.1"
    },
    {
        "description": "Croissant pressed in a waffle iron and topped with fresh whipped sweet cream, a drizzle of fruit puree and a cloud of cotton candy. Choice of three flavors: Banana Caramel \u2013 caramel drizzle with banana taffy cotton candy; Yuzu Meringue \u2013 yuzu puree with lemon meringue cotton candy; or Coconut Cream \u2013 coconut drizzle with coconut cotton candy.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-croffle-cloud.jpg",
        "slug": "99135086-b078-40ea-a026-030d0e5fb488",
        "id": "99135086-b078-40ea-a026-030d0e5fb488",
        "name": "Croffle Cloud",
        "vendor_slug": "5175.1"
    },
    {
        "description": "Bites of breaded tofu, deep fried and tossed in a tangy, spicy sauce. Served on a bed of pineapple and napa cabbage slaw. Topped with sesame seeds and scallions.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-deep-fried-tofuego-bites.jpg",
        "slug": "341c3f6c-8fd0-48da-a0ff-61b9037f8052",
        "id": "341c3f6c-8fd0-48da-a0ff-61b9037f8052",
        "name": "Deep-Fried Tofuego Bites",
        "vendor_slug": "792.1"
    },
    {
        "description": "Brewed black tea infused with dill pickle flavor and served with a dill pickle spear. Garnished with a rim of chamoy, Tajin, salt and dill. (Vegan, Gluten Free)",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-dill-pickle-iced-tea.jpg",
        "slug": "48b6ef7c-27af-4ffa-95ae-916088a2b158",
        "id": "48b6ef7c-27af-4ffa-95ae-916088a2b158",
        "name": "Dill Pickle Iced Tea",
        "vendor_slug": "3386.2"
    },
    {
        "description": "Falafel waffle, tahini butter, cherry tomatoes, traditional hummus, green shatta, mint, toasted sesame seeds",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-fawaffle.jpg",
        "slug": "fe11bd46-00b9-4395-9157-39e900952a8c",
        "id": "fe11bd46-00b9-4395-9157-39e900952a8c",
        "name": "Fawaffle",
        "vendor_slug": "5146.1"
    },
    {
        "description": "Fried chicken filled rolled tacos, served in a cup with warm salsa verde, crema & crumbly queso",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-flauta-dippers.png",
        "slug": "1baaab28-1d1b-49d4-90bb-81f62f49297e",
        "id": "1baaab28-1d1b-49d4-90bb-81f62f49297e",
        "name": "Flauta Dippers",
        "vendor_slug": "10312.2"
    },
    {
        "description": "Freaky Fryday features three pieces of Bacon fried chicken and three strips of chicken fried bacon! All vegan. Guests can choose from four topping options: dill pickle seasoning with ranch dressing, cinnamon sugar with maple syrup, spicy Dragon Dust with buffalo sauce, or a combination of all three.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-freaky-fryday.jpg",
        "slug": "bf6d05aa-3f5d-4723-ba32-ce1e99c4860e",
        "id": "bf6d05aa-3f5d-4723-ba32-ce1e99c4860e",
        "name": "Freaky Fryday",
        "vendor_slug": "5836.1"
    },
    {
        "description": "Oasis Mediterranean Grill will be serving up refreshing watermelon and Vimto slushies alongside their flavorful Somali Street Fries. Hoyo Sambusa offers handmade sambusas filled with savory meats or lentils, celebrating Somali tradition in every bite.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-2764.2.jpg",
        "slug": "6cead3a2-c69f-4c73-b6f9-44674b2ddb3e",
        "id": "6cead3a2-c69f-4c73-b6f9-44674b2ddb3e",
        "name": "Midtown Global Market's Indigenous Food Lab",
        "vendor_slug": "2764.2"
    },
    {
        "description": "Vanilla ice cream, created by Minnesota Dairy Lab, sandwiched between two pieces of Grandma Doreen\u2019s Coffee Cake \u2013 a family recipe from Elgin, Minn. \u2013 made by Wrecktangle Pizza. Skewered on-a-stick and drizzled with house-made strawberry rhubarb jam. Garnished with cinnamon toast-flavored crispy treats, whipped cream and sprinkles. (Vegetarian)",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-grandma-doreen\u2019s-dessert-dog.jpg",
        "slug": "f05eb0d3-3e60-499a-ab0c-9f644b5491f0",
        "id": "f05eb0d3-3e60-499a-ab0c-9f644b5491f0",
        "name": "Grandma Doreen's Dessert Dog",
        "vendor_slug": "3567.1"
    },
    {
        "description": "Tart green apple ice cream with swirls of sweet caramel \u2013 flavored like a caramel apple lollipop \u2013 served in a cup. Created by A to Z Creamery.",
        "image": "https://mnonastick.nyc3.digitaloceanspaces.com/prod/images/newthisyear-green-apple-sucker-ice-cream.jpg",
        "slug": "96e9fc16-654f-45fa-bc08-9bd3b2fac8ed",
        "id": "96e9fc16-654f-45fa-bc08-9bd3b2fac8ed",
        "name": "Green Apple Sucker Ice Cream",
        "vendor_slug": "11704.1"
    },
    {
